# Redirect HTTP to HTTPS
server {
    listen 80;
    server_name bscroller.navedu.uk www.bscroller.navedu.uk;
    return 301 https://$host$request_uri;
}

# HTTPS server
server {
    listen 443 ssl http2;
    server_name bscroller.navedu.uk www.bscroller.navedu.uk;

    client_max_body_size 50M;

    ssl_certificate /etc/ssl/cloudflare/bscroller_cert.pem;
    ssl_certificate_key /etc/ssl/cloudflare/bscroller_key.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location / {
        proxy_pass http://bscroller:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
