from __future__ import annotations

IQ_BOOK_IDS: dict[str, str] = {
    "Genesis": "01",
    "Exodus": "02",
    "Leviticus": "03",
    "Numbers": "04",
    "Deuteronomy": "05",
    "Joshua": "06",
    "Judges": "07",
    "Ruth": "08",
    "1 Samuel": "09",
    "2 Samuel": "10",
    "1 Kings": "11",
    "2 Kings": "12",
    "1 Chronicles": "13",
    "2 Chronicles": "14",
    "Ezra": "15",
    "Nehemiah": "16",
    "Esther": "17",
    "Job": "18",
    "Psalms": "19",
    "Psalm": "19",
    "Proverbs": "20",
    "Ecclesiastes": "21",
    "Song of Solomon": "22",
    "Song": "22",
    "Isaiah": "23",
    "Jeremiah": "24",
    "Lamentations": "25",
    "Ezekiel": "26",
    "Daniel": "27",
    "Hosea": "28",
    "Joel": "29",
    "Amos": "30",
    "Obadiah": "31",
    "Jonah": "32",
    "Micah": "33",
    "Nahum": "34",
    "Habakkuk": "35",
    "Zephaniah": "36",
    "Haggai": "37",
    "Zechariah": "38",
    "Malachi": "39",
    "Matthew": "40",
    "Mark": "41",
    "Luke": "42",
    "John": "43",
    "Acts": "44",
    "Romans": "45",
    "1 Corinthians": "46",
    "2 Corinthians": "47",
    "Galatians": "48",
    "Ephesians": "49",
    "Philippians": "50",
    "Colossians": "51",
    "1 Thessalonians": "52",
    "2 Thessalonians": "53",
    "1 Timothy": "54",
    "2 Timothy": "55",
    "Titus": "56",
    "Philemon": "57",
    "Hebrews": "58",
    "James": "59",
    "1 Peter": "60",
    "2 Peter": "61",
    "1 John": "62",
    "2 John": "63",
    "3 John": "64",
    "Jude": "65",
    "Revelation": "66",
}


def iq_book_id(book: str) -> str:
    normalized = book.strip()
    if normalized not in IQ_BOOK_IDS:
        raise ValueError(f"Unknown book for IQ Bible mapping: {book!r}")
    return IQ_BOOK_IDS[normalized]


def iq_verse_id(book: str, chapter: int, verse: int) -> str:
    return f"{iq_book_id(book)}{chapter:03d}{verse:03d}"


DBP_BOOK_IDS: dict[str, str] = {
    "Genesis": "GEN",
    "Exodus": "EXO",
    "Leviticus": "LEV",
    "Numbers": "NUM",
    "Deuteronomy": "DEU",
    "Joshua": "JOS",
    "Judges": "JDG",
    "Ruth": "RUT",
    "1 Samuel": "1SA",
    "2 Samuel": "2SA",
    "1 Kings": "1KI",
    "2 Kings": "2KI",
    "1 Chronicles": "1CH",
    "2 Chronicles": "2CH",
    "Ezra": "EZR",
    "Nehemiah": "NEH",
    "Esther": "EST",
    "Job": "JOB",
    "Psalms": "PSA",
    "Psalm": "PSA",
    "Proverbs": "PRO",
    "Ecclesiastes": "ECC",
    "Song of Solomon": "SNG",
    "Song": "SNG",
    "Isaiah": "ISA",
    "Jeremiah": "JER",
    "Lamentations": "LAM",
    "Ezekiel": "EZK",
    "Daniel": "DAN",
    "Hosea": "HOS",
    "Joel": "JOL",
    "Amos": "AMO",
    "Obadiah": "OBA",
    "Jonah": "JON",
    "Micah": "MIC",
    "Nahum": "NAH",
    "Habakkuk": "HAB",
    "Zephaniah": "ZEP",
    "Haggai": "HAG",
    "Zechariah": "ZEC",
    "Malachi": "MAL",
    "Matthew": "MAT",
    "Mark": "MRK",
    "Luke": "LUK",
    "John": "JHN",
    "Acts": "ACT",
    "Romans": "ROM",
    "1 Corinthians": "1CO",
    "2 Corinthians": "2CO",
    "Galatians": "GAL",
    "Ephesians": "EPH",
    "Philippians": "PHP",
    "Colossians": "COL",
    "1 Thessalonians": "1TH",
    "2 Thessalonians": "2TH",
    "1 Timothy": "1TI",
    "2 Timothy": "2TI",
    "Titus": "TIT",
    "Philemon": "PHM",
    "Hebrews": "HEB",
    "James": "JAS",
    "1 Peter": "1PE",
    "2 Peter": "2PE",
    "1 John": "1JN",
    "2 John": "2JN",
    "3 John": "3JN",
    "Jude": "JUD",
    "Revelation": "REV",
}


def dbp_book_id(book: str) -> str:
    normalized = book.strip()
    if normalized not in DBP_BOOK_IDS:
        raise ValueError(f"Unknown book for Bible Brain mapping: {book!r}")
    return DBP_BOOK_IDS[normalized]
